#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x5a7ba343, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x92b57248, __VMLINUX_SYMBOL_STR(flush_work) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0x76090a0, __VMLINUX_SYMBOL_STR(drm_atomic_get_connector_state) },
	{ 0x6c4c447, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x70a208bb, __VMLINUX_SYMBOL_STR(drm_atomic_legacy_backoff) },
	{ 0xfd60df2, __VMLINUX_SYMBOL_STR(drm_get_connector_status_name) },
	{ 0xcbe561a2, __VMLINUX_SYMBOL_STR(drm_calc_timestamping_constants) },
	{ 0x2c4cf8df, __VMLINUX_SYMBOL_STR(drm_get_edid) },
	{ 0x74401d34, __VMLINUX_SYMBOL_STR(drm_crtc_index) },
	{ 0x91fec1cc, __VMLINUX_SYMBOL_STR(drm_rect_calc_vscale) },
	{ 0x349cba85, __VMLINUX_SYMBOL_STR(strchr) },
	{ 0xde246a46, __VMLINUX_SYMBOL_STR(drm_framebuffer_reference) },
	{ 0xe7dbffbf, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0x43e74948, __VMLINUX_SYMBOL_STR(drm_bridge_disable) },
	{ 0xb1db6fc4, __VMLINUX_SYMBOL_STR(drm_edid_to_eld) },
	{ 0x660f5dcd, __VMLINUX_SYMBOL_STR(drm_mode_create_from_cmdline_mode) },
	{ 0x97255bdf, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x5b67fa87, __VMLINUX_SYMBOL_STR(framebuffer_release) },
	{ 0xff9677d2, __VMLINUX_SYMBOL_STR(drm_gem_cma_create) },
	{ 0x8de13715, __VMLINUX_SYMBOL_STR(drm_format_vert_chroma_subsampling) },
	{ 0x65d74ce7, __VMLINUX_SYMBOL_STR(drm_bridge_pre_enable) },
	{ 0x44450ab8, __VMLINUX_SYMBOL_STR(unlink_framebuffer) },
	{ 0xd6ade5ff, __VMLINUX_SYMBOL_STR(drm_atomic_state_clear) },
	{ 0xd3dbfbc4, __VMLINUX_SYMBOL_STR(_find_first_zero_bit_le) },
	{ 0xac0de731, __VMLINUX_SYMBOL_STR(drm_mode_destroy) },
	{ 0x4d974b9c, __VMLINUX_SYMBOL_STR(register_sysrq_key) },
	{ 0x13365238, __VMLINUX_SYMBOL_STR(drm_atomic_connectors_for_crtc) },
	{ 0x5d558894, __VMLINUX_SYMBOL_STR(drm_atomic_get_plane_state) },
	{ 0xd44af49e, __VMLINUX_SYMBOL_STR(fb_sys_read) },
	{ 0xf1421d13, __VMLINUX_SYMBOL_STR(drm_mode_sort) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0xc1c6ecd1, __VMLINUX_SYMBOL_STR(fence_wait_timeout) },
	{ 0x59fd151c, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0xe2fae716, __VMLINUX_SYMBOL_STR(kmemdup) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0xa530ec5d, __VMLINUX_SYMBOL_STR(cfb_fillrect) },
	{ 0x3186a04b, __VMLINUX_SYMBOL_STR(param_ops_bool) },
	{ 0x9580deb, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x4c29dcbf, __VMLINUX_SYMBOL_STR(cancel_delayed_work_sync) },
	{ 0x62b72b0d, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x85df9b6c, __VMLINUX_SYMBOL_STR(strsep) },
	{ 0xb657f169, __VMLINUX_SYMBOL_STR(drm_plane_force_disable) },
	{ 0xca45efbc, __VMLINUX_SYMBOL_STR(drm_format_horz_chroma_subsampling) },
	{ 0xd6b2f75, __VMLINUX_SYMBOL_STR(platform_device_register_full) },
	{ 0x86bb3e0a, __VMLINUX_SYMBOL_STR(drm_object_property_set_value) },
	{ 0xe590e273, __VMLINUX_SYMBOL_STR(sys_copyarea) },
	{ 0x8f696aed, __VMLINUX_SYMBOL_STR(drm_mode_validate_basic) },
	{ 0x37e74642, __VMLINUX_SYMBOL_STR(get_jiffies_64) },
	{ 0xc499ae1e, __VMLINUX_SYMBOL_STR(kstrdup) },
	{ 0x5ce43146, __VMLINUX_SYMBOL_STR(drm_universal_plane_init) },
	{ 0xf737d13c, __VMLINUX_SYMBOL_STR(drm_atomic_set_mode_prop_for_crtc) },
	{ 0xb2d7c30e, __VMLINUX_SYMBOL_STR(i2c_add_adapter) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0x131db64a, __VMLINUX_SYMBOL_STR(system_long_wq) },
	{ 0xe842ad1e, __VMLINUX_SYMBOL_STR(param_ops_string) },
	{ 0x4ea51f93, __VMLINUX_SYMBOL_STR(drm_atomic_set_mode_for_crtc) },
	{ 0xb7617569, __VMLINUX_SYMBOL_STR(fb_set_suspend) },
	{ 0x63b87fc5, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0xd2335101, __VMLINUX_SYMBOL_STR(drm_fb_get_bpp_depth) },
	{ 0xe707d823, __VMLINUX_SYMBOL_STR(__aeabi_uidiv) },
	{ 0x59ef50f0, __VMLINUX_SYMBOL_STR(drm_edid_block_valid) },
	{ 0xdd0a2ba2, __VMLINUX_SYMBOL_STR(strlcat) },
	{ 0x88ab6fe3, __VMLINUX_SYMBOL_STR(kgdb_active) },
	{ 0x7139f8a9, __VMLINUX_SYMBOL_STR(drm_bridge_post_disable) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0x95e6da0b, __VMLINUX_SYMBOL_STR(drm_atomic_crtc_set_property) },
	{ 0x5f754e5a, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xa310a42d, __VMLINUX_SYMBOL_STR(drm_atomic_state_alloc) },
	{ 0x66a7444f, __VMLINUX_SYMBOL_STR(drm_mode_copy) },
	{ 0x460001e1, __VMLINUX_SYMBOL_STR(drm_atomic_commit) },
	{ 0x60a82f35, __VMLINUX_SYMBOL_STR(drm_mode_find_dmt) },
	{ 0x8a69cd1e, __VMLINUX_SYMBOL_STR(drm_plane_index) },
	{ 0x3ac81370, __VMLINUX_SYMBOL_STR(cfb_imageblit) },
	{ 0xcea122c0, __VMLINUX_SYMBOL_STR(dev_err) },
	{ 0xcde46cc0, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_put) },
	{ 0x94f285a7, __VMLINUX_SYMBOL_STR(drm_bridge_enable) },
	{ 0xdc798d37, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x96533674, __VMLINUX_SYMBOL_STR(drm_mode_duplicate) },
	{ 0x7a890c8, __VMLINUX_SYMBOL_STR(fb_alloc_cmap) },
	{ 0x7260646f, __VMLINUX_SYMBOL_STR(drm_crtc_init_with_planes) },
	{ 0x5152e605, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x72a08a28, __VMLINUX_SYMBOL_STR(drm_atomic_set_crtc_for_connector) },
	{ 0xdcd882dd, __VMLINUX_SYMBOL_STR(drm_gem_handle_create) },
	{ 0x563c1d04, __VMLINUX_SYMBOL_STR(drm_atomic_state_free) },
	{ 0x46e6b4b8, __VMLINUX_SYMBOL_STR(drm_atomic_plane_set_property) },
	{ 0xf369c549, __VMLINUX_SYMBOL_STR(drm_property_unreference_blob) },
	{ 0x18399aa6, __VMLINUX_SYMBOL_STR(register_framebuffer) },
	{ 0xa1c76e0a, __VMLINUX_SYMBOL_STR(_cond_resched) },
	{ 0x84b183ae, __VMLINUX_SYMBOL_STR(strncmp) },
	{ 0x73e20c1c, __VMLINUX_SYMBOL_STR(strlcpy) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xe16b893b, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x8d3beb55, __VMLINUX_SYMBOL_STR(drm_framebuffer_unreference) },
	{ 0x238387f, __VMLINUX_SYMBOL_STR(drm_modeset_legacy_acquire_ctx) },
	{ 0x6b0297cf, __VMLINUX_SYMBOL_STR(drm_add_edid_modes) },
	{ 0x710dfdf, __VMLINUX_SYMBOL_STR(platform_device_unregister) },
	{ 0x8e865d3c, __VMLINUX_SYMBOL_STR(arm_delay_ops) },
	{ 0x7c82dec2, __VMLINUX_SYMBOL_STR(drm_atomic_set_fb_for_plane) },
	{ 0x1dd71f7a, __VMLINUX_SYMBOL_STR(drm_err) },
	{ 0x2196324, __VMLINUX_SYMBOL_STR(__aeabi_idiv) },
	{ 0xc6e3ef74, __VMLINUX_SYMBOL_STR(drm_mode_connector_update_edid_property) },
	{ 0x9eef5a54, __VMLINUX_SYMBOL_STR(drm_modeset_lock) },
	{ 0x20645642, __VMLINUX_SYMBOL_STR(drm_debug) },
	{ 0x7fab7817, __VMLINUX_SYMBOL_STR(drm_mode_validate_size) },
	{ 0x7fc871b2, __VMLINUX_SYMBOL_STR(drm_crtc_wait_one_vblank) },
	{ 0x8f5f71a4, __VMLINUX_SYMBOL_STR(drm_crtc_get_hv_timing) },
	{ 0x4ea1f5a2, __VMLINUX_SYMBOL_STR(drm_gem_object_free) },
	{ 0xf13bc977, __VMLINUX_SYMBOL_STR(drm_mode_connector_list_update) },
	{ 0xd5163ec4, __VMLINUX_SYMBOL_STR(drm_atomic_get_crtc_state) },
	{ 0x98b71c6, __VMLINUX_SYMBOL_STR(fb_dealloc_cmap) },
	{ 0x4059792f, __VMLINUX_SYMBOL_STR(print_hex_dump) },
	{ 0xb28d932, __VMLINUX_SYMBOL_STR(i2c_del_adapter) },
	{ 0x98626ca4, __VMLINUX_SYMBOL_STR(drm_mode_set_crtcinfo) },
	{ 0x5d3a7dd8, __VMLINUX_SYMBOL_STR(drm_plane_cleanup) },
	{ 0xb1c3a01a, __VMLINUX_SYMBOL_STR(oops_in_progress) },
	{ 0x48df6c8f, __VMLINUX_SYMBOL_STR(_dev_info) },
	{ 0xd5d24edd, __VMLINUX_SYMBOL_STR(drm_mode_prune_invalid) },
	{ 0x8e0159fa, __VMLINUX_SYMBOL_STR(drm_atomic_set_crtc_for_plane) },
	{ 0x12a38747, __VMLINUX_SYMBOL_STR(usleep_range) },
	{ 0xb350108b, __VMLINUX_SYMBOL_STR(sys_fillrect) },
	{ 0xa413a109, __VMLINUX_SYMBOL_STR(drm_framebuffer_unregister_private) },
	{ 0x3f616ce2, __VMLINUX_SYMBOL_STR(queue_delayed_work_on) },
	{ 0x59aa14cf, __VMLINUX_SYMBOL_STR(fence_release) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0xbf40f4bb, __VMLINUX_SYMBOL_STR(sys_imageblit) },
	{ 0xb1f3a2f, __VMLINUX_SYMBOL_STR(drm_sysfs_hotplug_event) },
	{ 0x38a4f7ae, __VMLINUX_SYMBOL_STR(drm_format_num_planes) },
	{ 0xd5793fc, __VMLINUX_SYMBOL_STR(fb_sys_write) },
	{ 0x4780c5ee, __VMLINUX_SYMBOL_STR(drm_mode_debug_printmodeline) },
	{ 0x8ba5179a, __VMLINUX_SYMBOL_STR(drm_bridge_mode_fixup) },
	{ 0xe9226938, __VMLINUX_SYMBOL_STR(drm_gem_object_lookup) },
	{ 0x7aa9f60c, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_get) },
	{ 0x36750050, __VMLINUX_SYMBOL_STR(drm_add_modes_noedid) },
	{ 0x3b9d009a, __VMLINUX_SYMBOL_STR(drm_format_plane_cpp) },
	{ 0x7ae1139b, __VMLINUX_SYMBOL_STR(drm_atomic_connector_set_property) },
	{ 0x9777bbd5, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xc1731e2b, __VMLINUX_SYMBOL_STR(drm_warn_on_modeset_not_all_locked) },
	{ 0x7349c5cd, __VMLINUX_SYMBOL_STR(drm_atomic_clean_old_fb) },
	{ 0x72c00541, __VMLINUX_SYMBOL_STR(drm_gem_cma_describe) },
	{ 0xb9e52429, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x3d31c2f2, __VMLINUX_SYMBOL_STR(framebuffer_alloc) },
	{ 0x158f2f00, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0xf21373dd, __VMLINUX_SYMBOL_STR(drm_mode_set_config_internal) },
	{ 0xa28078b2, __VMLINUX_SYMBOL_STR(drm_edid_duplicate) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x6900d335, __VMLINUX_SYMBOL_STR(drm_rect_clip_scaled) },
	{ 0x2256fafa, __VMLINUX_SYMBOL_STR(div64_u64_rem) },
	{ 0xd7d7ed5, __VMLINUX_SYMBOL_STR(drm_mode_equal) },
	{ 0x70245ed7, __VMLINUX_SYMBOL_STR(request_firmware) },
	{ 0x6fb790d2, __VMLINUX_SYMBOL_STR(drm_modeset_lock_all) },
	{ 0x8893fa5d, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0xa1cc3d2d, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_count) },
	{ 0x2d50570f, __VMLINUX_SYMBOL_STR(drm_rect_calc_hscale) },
	{ 0xf3f01ea5, __VMLINUX_SYMBOL_STR(cfb_copyarea) },
	{ 0x6fed6b15, __VMLINUX_SYMBOL_STR(drm_atomic_add_affected_connectors) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0x17399f5d, __VMLINUX_SYMBOL_STR(drm_mode_probed_add) },
	{ 0xb2d48a2e, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0xb81960ca, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0xa4885c26, __VMLINUX_SYMBOL_STR(drm_modeset_unlock_all) },
	{ 0x1b6c972b, __VMLINUX_SYMBOL_STR(drm_bridge_mode_set) },
	{ 0xc5960d51, __VMLINUX_SYMBOL_STR(drm_mode_plane_set_obj_prop) },
	{ 0xcc619b29, __VMLINUX_SYMBOL_STR(drm_atomic_add_affected_planes) },
	{ 0xaccd8d71, __VMLINUX_SYMBOL_STR(drm_framebuffer_init) },
	{ 0x9d26e891, __VMLINUX_SYMBOL_STR(drm_mode_connector_set_tile_property) },
	{ 0xc360e7e2, __VMLINUX_SYMBOL_STR(drm_ut_debug_printk) },
	{ 0x49ebacbd, __VMLINUX_SYMBOL_STR(_clear_bit) },
	{ 0xcbc9557f, __VMLINUX_SYMBOL_STR(unregister_sysrq_key) },
	{ 0x3ac1fef9, __VMLINUX_SYMBOL_STR(drm_mode_legacy_fb_format) },
	{ 0xd25fda63, __VMLINUX_SYMBOL_STR(release_firmware) },
	{ 0xb859f38b, __VMLINUX_SYMBOL_STR(krealloc) },
	{ 0x8560a730, __VMLINUX_SYMBOL_STR(drm_mode_vrefresh) },
	{ 0x6b8efaa0, __VMLINUX_SYMBOL_STR(drm_property_reference_blob) },
	{ 0x465ee4a8, __VMLINUX_SYMBOL_STR(drm_atomic_async_commit) },
	{ 0xb56bcbcc, __VMLINUX_SYMBOL_STR(drm_framebuffer_cleanup) },
	{ 0xf4b1b75a, __VMLINUX_SYMBOL_STR(unregister_framebuffer) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=drm,fb_sys_fops,syscopyarea,sysfillrect,sysimgblt";


MODULE_INFO(srcversion, "7979999D268BF6CF9C3D15D");
