#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x5a7ba343, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xb077e70a, __VMLINUX_SYMBOL_STR(clk_unprepare) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0xcb0e0957, __VMLINUX_SYMBOL_STR(drm_gem_prime_export) },
	{ 0xce102fc0, __VMLINUX_SYMBOL_STR(rpi_firmware_transaction) },
	{ 0xebd4191e, __VMLINUX_SYMBOL_STR(component_match_add) },
	{ 0x7dc549d4, __VMLINUX_SYMBOL_STR(drm_release) },
	{ 0x6c4c447, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xffc65e5c, __VMLINUX_SYMBOL_STR(perf_tp_event) },
	{ 0xf9a482f9, __VMLINUX_SYMBOL_STR(msleep) },
	{ 0x9c0b8248, __VMLINUX_SYMBOL_STR(cma_get_size) },
	{ 0xb305ea25, __VMLINUX_SYMBOL_STR(drm_dev_register) },
	{ 0x815588a6, __VMLINUX_SYMBOL_STR(clk_enable) },
	{ 0x219bf7d5, __VMLINUX_SYMBOL_STR(of_find_i2c_adapter_by_node) },
	{ 0x2c4cf8df, __VMLINUX_SYMBOL_STR(drm_get_edid) },
	{ 0xdfb265d5, __VMLINUX_SYMBOL_STR(drm_atomic_helper_update_plane) },
	{ 0x74401d34, __VMLINUX_SYMBOL_STR(drm_crtc_index) },
	{ 0x20e4cc3c, __VMLINUX_SYMBOL_STR(drm_atomic_helper_crtc_duplicate_state) },
	{ 0x216b1265, __VMLINUX_SYMBOL_STR(__pm_runtime_disable) },
	{ 0xa059d01d, __VMLINUX_SYMBOL_STR(drm_calc_vbltimestamp_from_scanoutpos) },
	{ 0xde246a46, __VMLINUX_SYMBOL_STR(drm_framebuffer_reference) },
	{ 0xbacbed6d, __VMLINUX_SYMBOL_STR(drm_dev_alloc) },
	{ 0x88074797, __VMLINUX_SYMBOL_STR(component_unbind_all) },
	{ 0x7aa1756e, __VMLINUX_SYMBOL_STR(kvfree) },
	{ 0x8ea69e7, __VMLINUX_SYMBOL_STR(mipi_dsi_packet_format_is_long) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0x6c09c2a4, __VMLINUX_SYMBOL_STR(del_timer) },
	{ 0x531a1854, __VMLINUX_SYMBOL_STR(__pm_runtime_use_autosuspend) },
	{ 0xff9677d2, __VMLINUX_SYMBOL_STR(drm_gem_cma_create) },
	{ 0x8de13715, __VMLINUX_SYMBOL_STR(drm_format_vert_chroma_subsampling) },
	{ 0x234fcb0d, __VMLINUX_SYMBOL_STR(drm_mode_config_cleanup) },
	{ 0x4828084, __VMLINUX_SYMBOL_STR(component_add) },
	{ 0x7aab607e, __VMLINUX_SYMBOL_STR(__pm_runtime_suspend) },
	{ 0x9ce65b56, __VMLINUX_SYMBOL_STR(of_parse_phandle) },
	{ 0x2704afac, __VMLINUX_SYMBOL_STR(drm_mode_config_reset) },
	{ 0xc8b57c27, __VMLINUX_SYMBOL_STR(autoremove_wake_function) },
	{ 0x604f3b2e, __VMLINUX_SYMBOL_STR(drm_atomic_helper_connector_reset) },
	{ 0xc5303fb3, __VMLINUX_SYMBOL_STR(arm_dma_ops) },
	{ 0x1ebe2f10, __VMLINUX_SYMBOL_STR(drm_gem_cma_prime_mmap) },
	{ 0xb060e256, __VMLINUX_SYMBOL_STR(drm_atomic_helper_page_flip) },
	{ 0x1c5c5370, __VMLINUX_SYMBOL_STR(drm_match_cea_mode) },
	{ 0x13365238, __VMLINUX_SYMBOL_STR(drm_atomic_connectors_for_crtc) },
	{ 0x5cc509a4, __VMLINUX_SYMBOL_STR(nsecs_to_jiffies) },
	{ 0x2f47932, __VMLINUX_SYMBOL_STR(drm_atomic_helper_swap_state) },
	{ 0xb6e6d99d, __VMLINUX_SYMBOL_STR(clk_disable) },
	{ 0xf8bc5f6f, __VMLINUX_SYMBOL_STR(drm_cvt_mode) },
	{ 0x95c8d302, __VMLINUX_SYMBOL_STR(drm_crtc_handle_vblank) },
	{ 0x788c2bf1, __VMLINUX_SYMBOL_STR(gpio_to_desc) },
	{ 0x4fe38dbd, __VMLINUX_SYMBOL_STR(down_interruptible) },
	{ 0x4ae2c513, __VMLINUX_SYMBOL_STR(drm_helper_probe_single_connector_modes) },
	{ 0x59fd151c, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x13a13e55, __VMLINUX_SYMBOL_STR(mipi_dsi_host_unregister) },
	{ 0xe219dfc9, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_off) },
	{ 0x4205ad24, __VMLINUX_SYMBOL_STR(cancel_work_sync) },
	{ 0xc87c1f84, __VMLINUX_SYMBOL_STR(ktime_get) },
	{ 0x3c293082, __VMLINUX_SYMBOL_STR(platform_bus_type) },
	{ 0x165c3262, __VMLINUX_SYMBOL_STR(component_bind_all) },
	{ 0xe2fae716, __VMLINUX_SYMBOL_STR(kmemdup) },
	{ 0x6f5e82cd, __VMLINUX_SYMBOL_STR(drm_fbdev_cma_init) },
	{ 0x8ada9ccd, __VMLINUX_SYMBOL_STR(devm_ioremap_resource) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0x92a258df, __VMLINUX_SYMBOL_STR(debugfs_print_regs32) },
	{ 0x36fdda67, __VMLINUX_SYMBOL_STR(hdmi_infoframe_pack) },
	{ 0x9580deb, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x28cc25db, __VMLINUX_SYMBOL_STR(arm_copy_from_user) },
	{ 0x62b72b0d, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xe4c4db4f, __VMLINUX_SYMBOL_STR(drm_vblank_no_hw_counter) },
	{ 0x1b4b507c, __VMLINUX_SYMBOL_STR(__pm_runtime_resume) },
	{ 0x4772b8d9, __VMLINUX_SYMBOL_STR(trace_event_buffer_reserve) },
	{ 0x9802feb3, __VMLINUX_SYMBOL_STR(drm_dev_unref) },
	{ 0x844ca90f, __VMLINUX_SYMBOL_STR(drm_vblank_init) },
	{ 0x7f5ad75c, __VMLINUX_SYMBOL_STR(component_master_del) },
	{ 0xca45efbc, __VMLINUX_SYMBOL_STR(drm_format_horz_chroma_subsampling) },
	{ 0x16985ce9, __VMLINUX_SYMBOL_STR(drm_encoder_init) },
	{ 0x25e2d059, __VMLINUX_SYMBOL_STR(drm_gem_cma_prime_get_sg_table) },
	{ 0x556e4390, __VMLINUX_SYMBOL_STR(clk_get_rate) },
	{ 0xd697e69a, __VMLINUX_SYMBOL_STR(trace_hardirqs_on) },
	{ 0x3502982c, __VMLINUX_SYMBOL_STR(drm_atomic_helper_crtc_reset) },
	{ 0x5ce43146, __VMLINUX_SYMBOL_STR(drm_universal_plane_init) },
	{ 0x17c50734, __VMLINUX_SYMBOL_STR(__platform_driver_register) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x92806bd2, __VMLINUX_SYMBOL_STR(drm_gem_cma_vm_ops) },
	{ 0x104633d9, __VMLINUX_SYMBOL_STR(drm_connector_cleanup) },
	{ 0xf4fa543b, __VMLINUX_SYMBOL_STR(arm_copy_to_user) },
	{ 0xedfd036, __VMLINUX_SYMBOL_STR(__drm_atomic_helper_plane_duplicate_state) },
	{ 0x7ce59f4d, __VMLINUX_SYMBOL_STR(drm_atomic_helper_connector_duplicate_state) },
	{ 0x16721feb, __VMLINUX_SYMBOL_STR(__drm_atomic_helper_crtc_duplicate_state) },
	{ 0x63b87fc5, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x849ce87b, __VMLINUX_SYMBOL_STR(drm_atomic_helper_set_config) },
	{ 0xe707d823, __VMLINUX_SYMBOL_STR(__aeabi_uidiv) },
	{ 0x88ab6fe3, __VMLINUX_SYMBOL_STR(kgdb_active) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0xd793a0cb, __VMLINUX_SYMBOL_STR(trace_define_field) },
	{ 0x1a546ddd, __VMLINUX_SYMBOL_STR(drm_mm_init) },
	{ 0xf652ae73, __VMLINUX_SYMBOL_STR(drm_mode_connector_attach_encoder) },
	{ 0x92221f11, __VMLINUX_SYMBOL_STR(drm_irq_install) },
	{ 0xafc7868a, __VMLINUX_SYMBOL_STR(of_clk_src_onecell_get) },
	{ 0x504415ab, __VMLINUX_SYMBOL_STR(devm_clk_register) },
	{ 0x429be6d3, __VMLINUX_SYMBOL_STR(remove_conflicting_framebuffers) },
	{ 0x732b5dcf, __VMLINUX_SYMBOL_STR(drm_dev_unregister) },
	{ 0x8a69cd1e, __VMLINUX_SYMBOL_STR(drm_plane_index) },
	{ 0xcc337fd5, __VMLINUX_SYMBOL_STR(drm_fbdev_cma_restore_mode) },
	{ 0xcea122c0, __VMLINUX_SYMBOL_STR(dev_err) },
	{ 0x8692a004, __VMLINUX_SYMBOL_STR(down_trylock) },
	{ 0xcde46cc0, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_put) },
	{ 0xdc798d37, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xd9222e3a, __VMLINUX_SYMBOL_STR(drm_atomic_helper_prepare_planes) },
	{ 0x7260646f, __VMLINUX_SYMBOL_STR(drm_crtc_init_with_planes) },
	{ 0x86d928b8, __VMLINUX_SYMBOL_STR(drm_put_dev) },
	{ 0x9cc38d59, __VMLINUX_SYMBOL_STR(of_graph_get_next_endpoint) },
	{ 0xb2e371ba, __VMLINUX_SYMBOL_STR(drm_atomic_helper_plane_reset) },
	{ 0x5f1c699a, __VMLINUX_SYMBOL_STR(of_find_property) },
	{ 0xdcd882dd, __VMLINUX_SYMBOL_STR(drm_gem_handle_create) },
	{ 0xe728a35d, __VMLINUX_SYMBOL_STR(drm_gem_dumb_destroy) },
	{ 0xa0df3d15, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_on) },
	{ 0x563c1d04, __VMLINUX_SYMBOL_STR(drm_atomic_state_free) },
	{ 0xaa8014df, __VMLINUX_SYMBOL_STR(dma_sync_wait) },
	{ 0x2e3af3fd, __VMLINUX_SYMBOL_STR(drm_fb_cma_get_gem_obj) },
	{ 0x9a191433, __VMLINUX_SYMBOL_STR(trace_event_reg) },
	{ 0x10a6c59, __VMLINUX_SYMBOL_STR(drm_panel_attach) },
	{ 0xb2c912af, __VMLINUX_SYMBOL_STR(drm_fbdev_cma_hotplug_event) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xe16b893b, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x6dc488ae, __VMLINUX_SYMBOL_STR(drm_probe_ddc) },
	{ 0xad05c940, __VMLINUX_SYMBOL_STR(drm_fb_cma_create) },
	{ 0x8d3beb55, __VMLINUX_SYMBOL_STR(drm_framebuffer_unreference) },
	{ 0x9fd284a0, __VMLINUX_SYMBOL_STR(platform_get_resource) },
	{ 0x9d933e5c, __VMLINUX_SYMBOL_STR(drm_read) },
	{ 0x67633846, __VMLINUX_SYMBOL_STR(drm_mm_insert_node_generic) },
	{ 0x96a1d7e5, __VMLINUX_SYMBOL_STR(noop_llseek) },
	{ 0x16e5c2a, __VMLINUX_SYMBOL_STR(mod_timer) },
	{ 0x6b0297cf, __VMLINUX_SYMBOL_STR(drm_add_edid_modes) },
	{ 0x1a871639, __VMLINUX_SYMBOL_STR(of_clk_add_provider) },
	{ 0x8e865d3c, __VMLINUX_SYMBOL_STR(arm_delay_ops) },
	{ 0x85c667af, __VMLINUX_SYMBOL_STR(bus_find_device) },
	{ 0x7c82dec2, __VMLINUX_SYMBOL_STR(drm_atomic_set_fb_for_plane) },
	{ 0xf4e97b1a, __VMLINUX_SYMBOL_STR(rpi_firmware_property) },
	{ 0xc63a4adb, __VMLINUX_SYMBOL_STR(drm_debugfs_create_files) },
	{ 0x1dd71f7a, __VMLINUX_SYMBOL_STR(drm_err) },
	{ 0x598d19fb, __VMLINUX_SYMBOL_STR(drm_connector_init) },
	{ 0xae46bb6, __VMLINUX_SYMBOL_STR(of_match_device) },
	{ 0xc6e3ef74, __VMLINUX_SYMBOL_STR(drm_mode_connector_update_edid_property) },
	{ 0xa30069ba, __VMLINUX_SYMBOL_STR(dma_alloc_from_coherent) },
	{ 0x6bea8226, __VMLINUX_SYMBOL_STR(drm_gem_vm_close) },
	{ 0x20645642, __VMLINUX_SYMBOL_STR(drm_debug) },
	{ 0x4ea1f5a2, __VMLINUX_SYMBOL_STR(drm_gem_object_free) },
	{ 0x99881acd, __VMLINUX_SYMBOL_STR(drm_gem_prime_fd_to_handle) },
	{ 0x7da9aa15, __VMLINUX_SYMBOL_STR(of_get_address) },
	{ 0x4925f71f, __VMLINUX_SYMBOL_STR(drm_plane_helper_disable) },
	{ 0x286c0545, __VMLINUX_SYMBOL_STR(gpiod_get_raw_value_cansleep) },
	{ 0x5d3a7dd8, __VMLINUX_SYMBOL_STR(drm_plane_cleanup) },
	{ 0x703103f, __VMLINUX_SYMBOL_STR(drm_ioctl) },
	{ 0x641077f8, __VMLINUX_SYMBOL_STR(drm_gem_prime_import) },
	{ 0x48df6c8f, __VMLINUX_SYMBOL_STR(_dev_info) },
	{ 0xf0142e77, __VMLINUX_SYMBOL_STR(drm_gem_mmap) },
	{ 0x57e8ac84, __VMLINUX_SYMBOL_STR(drm_atomic_helper_plane_duplicate_state) },
	{ 0x8fc796ea, __VMLINUX_SYMBOL_STR(idr_find_slowpath) },
	{ 0xc743472b, __VMLINUX_SYMBOL_STR(drm_atomic_helper_wait_for_vblanks) },
	{ 0x7e1550b2, __VMLINUX_SYMBOL_STR(drm_atomic_helper_connector_destroy_state) },
	{ 0x40686ba1, __VMLINUX_SYMBOL_STR(__drm_atomic_helper_plane_destroy_state) },
	{ 0x7092cea7, __VMLINUX_SYMBOL_STR(pm_runtime_enable) },
	{ 0x9b913cba, __VMLINUX_SYMBOL_STR(trace_event_ignore_this_pid) },
	{ 0x5ff17546, __VMLINUX_SYMBOL_STR(drm_atomic_helper_check) },
	{ 0xbb4f295d, __VMLINUX_SYMBOL_STR(put_device) },
	{ 0x8ed2b1a, __VMLINUX_SYMBOL_STR(drm_gem_cma_prime_vunmap) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0x4fd950ed, __VMLINUX_SYMBOL_STR(dma_contiguous_default_area) },
	{ 0xe6760a7a, __VMLINUX_SYMBOL_STR(drm_irq_uninstall) },
	{ 0x38a4f7ae, __VMLINUX_SYMBOL_STR(drm_format_num_planes) },
	{ 0x7c9a7371, __VMLINUX_SYMBOL_STR(clk_prepare) },
	{ 0x34a6ba50, __VMLINUX_SYMBOL_STR(drm_atomic_helper_commit_modeset_disables) },
	{ 0x47b551f2, __VMLINUX_SYMBOL_STR(drm_crtc_send_vblank_event) },
	{ 0x50fad434, __VMLINUX_SYMBOL_STR(round_jiffies_up) },
	{ 0xe9226938, __VMLINUX_SYMBOL_STR(drm_gem_object_lookup) },
	{ 0x7aa9f60c, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_get) },
	{ 0xd8500d20, __VMLINUX_SYMBOL_STR(of_get_named_gpio_flags) },
	{ 0x39d64870, __VMLINUX_SYMBOL_STR(trace_event_buffer_commit) },
	{ 0x7f24de73, __VMLINUX_SYMBOL_STR(jiffies_to_usecs) },
	{ 0x3b9d009a, __VMLINUX_SYMBOL_STR(drm_format_plane_cpp) },
	{ 0xa3248112, __VMLINUX_SYMBOL_STR(__dma_request_channel) },
	{ 0x38a89bb5, __VMLINUX_SYMBOL_STR(devm_clk_get) },
	{ 0x9777bbd5, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x1a770ac3, __VMLINUX_SYMBOL_STR(drm_detect_hdmi_monitor) },
	{ 0x11801e90, __VMLINUX_SYMBOL_STR(drm_atomic_helper_connector_dpms) },
	{ 0xc3dbe906, __VMLINUX_SYMBOL_STR(drm_gem_prime_handle_to_fd) },
	{ 0x2e47e3cc, __VMLINUX_SYMBOL_STR(rpi_firmware_get) },
	{ 0x76d9b876, __VMLINUX_SYMBOL_STR(clk_set_rate) },
	{ 0xb16dfe28, __VMLINUX_SYMBOL_STR(drm_gem_cma_prime_import_sg_table) },
	{ 0xb9e52429, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0xca07ac4b, __VMLINUX_SYMBOL_STR(event_triggers_call) },
	{ 0xaa8ecff4, __VMLINUX_SYMBOL_STR(drm_connector_unregister) },
	{ 0x9b403553, __VMLINUX_SYMBOL_STR(drm_encoder_cleanup) },
	{ 0x90016932, __VMLINUX_SYMBOL_STR(drm_dev_set_unique) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0xea700581, __VMLINUX_SYMBOL_STR(of_graph_get_remote_port_parent) },
	{ 0x4cd48b95, __VMLINUX_SYMBOL_STR(drm_crtc_cleanup) },
	{ 0xd9a6a10a, __VMLINUX_SYMBOL_STR(drm_atomic_helper_commit_planes) },
	{ 0x28d6861d, __VMLINUX_SYMBOL_STR(__vmalloc) },
	{ 0x31cdb549, __VMLINUX_SYMBOL_STR(drm_atomic_helper_crtc_destroy_state) },
	{ 0xaf8a3a0e, __VMLINUX_SYMBOL_STR(drm_mode_config_init) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xa3577293, __VMLINUX_SYMBOL_STR(drm_helper_hpd_irq_event) },
	{ 0x48bde478, __VMLINUX_SYMBOL_STR(drm_hdmi_avi_infoframe_from_display_mode) },
	{ 0x1810b087, __VMLINUX_SYMBOL_STR(component_del) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x5f8517b9, __VMLINUX_SYMBOL_STR(trace_event_raw_init) },
	{ 0x75a17bed, __VMLINUX_SYMBOL_STR(prepare_to_wait) },
	{ 0x1ff6c8b8, __VMLINUX_SYMBOL_STR(perf_trace_buf_prepare) },
	{ 0xf75c4d62, __VMLINUX_SYMBOL_STR(drm_panel_detach) },
	{ 0x364b3fff, __VMLINUX_SYMBOL_STR(up) },
	{ 0xb79ec15d, __VMLINUX_SYMBOL_STR(mipi_dsi_create_packet) },
	{ 0xea604bfd, __VMLINUX_SYMBOL_STR(drm_atomic_helper_cleanup_planes) },
	{ 0x1db7dc40, __VMLINUX_SYMBOL_STR(pgprot_kernel) },
	{ 0x6d32d563, __VMLINUX_SYMBOL_STR(drm_debugfs_remove_files) },
	{ 0xdd150721, __VMLINUX_SYMBOL_STR(drm_mm_takedown) },
	{ 0x8893fa5d, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x6b2636d3, __VMLINUX_SYMBOL_STR(dma_common_mmap) },
	{ 0xb0a97dcb, __VMLINUX_SYMBOL_STR(pm_runtime_set_autosuspend_delay) },
	{ 0x70b2ac36, __VMLINUX_SYMBOL_STR(dev_warn) },
	{ 0xc9d3ee27, __VMLINUX_SYMBOL_STR(drm_atomic_helper_disable_plane) },
	{ 0x7b3ea846, __VMLINUX_SYMBOL_STR(trace_raw_output_prep) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0x17399f5d, __VMLINUX_SYMBOL_STR(drm_mode_probed_add) },
	{ 0x1d927ac2, __VMLINUX_SYMBOL_STR(component_master_add_with_match) },
	{ 0xb2d48a2e, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0x60f71cfa, __VMLINUX_SYMBOL_STR(complete) },
	{ 0x1148b623, __VMLINUX_SYMBOL_STR(drm_fbdev_cma_fini) },
	{ 0xf147dcb2, __VMLINUX_SYMBOL_STR(hdmi_spd_infoframe_init) },
	{ 0xaef849af, __VMLINUX_SYMBOL_STR(platform_get_irq) },
	{ 0x3c93ea25, __VMLINUX_SYMBOL_STR(trace_seq_printf) },
	{ 0x82a4e5a6, __VMLINUX_SYMBOL_STR(of_drm_find_panel) },
	{ 0xb38ae9ce, __VMLINUX_SYMBOL_STR(platform_driver_unregister) },
	{ 0xa4466414, __VMLINUX_SYMBOL_STR(drm_mm_remove_node) },
	{ 0xc360e7e2, __VMLINUX_SYMBOL_STR(drm_ut_debug_printk) },
	{ 0x797aa246, __VMLINUX_SYMBOL_STR(drm_kms_helper_poll_init) },
	{ 0x915a1765, __VMLINUX_SYMBOL_STR(drm_gem_cma_free_object) },
	{ 0xde88c2a1, __VMLINUX_SYMBOL_STR(drm_gem_cma_prime_vmap) },
	{ 0x3f44f332, __VMLINUX_SYMBOL_STR(of_node_put) },
	{ 0x652fbf24, __VMLINUX_SYMBOL_STR(devm_kmalloc) },
	{ 0x80d817ab, __VMLINUX_SYMBOL_STR(wait_for_completion_timeout) },
	{ 0xec3d2e1b, __VMLINUX_SYMBOL_STR(trace_hardirqs_off) },
	{ 0x7b1ceca2, __VMLINUX_SYMBOL_STR(drm_connector_register) },
	{ 0x6cc72d94, __VMLINUX_SYMBOL_STR(devm_request_threaded_irq) },
	{ 0xa7e13f88, __VMLINUX_SYMBOL_STR(drm_atomic_helper_commit_modeset_enables) },
	{ 0x3254404d, __VMLINUX_SYMBOL_STR(drm_mode_crtc_set_gamma_size) },
	{ 0x10c0cff7, __VMLINUX_SYMBOL_STR(mipi_dsi_host_register) },
	{ 0xe4832020, __VMLINUX_SYMBOL_STR(drm_poll) },
	{ 0xc569d8ce, __VMLINUX_SYMBOL_STR(__clk_get_name) },
	{ 0xa29dfeb0, __VMLINUX_SYMBOL_STR(drm_gem_cma_dumb_map_offset) },
	{ 0x6f762933, __VMLINUX_SYMBOL_STR(cma_get_base) },
	{ 0xb859f38b, __VMLINUX_SYMBOL_STR(krealloc) },
	{ 0x2e7a4300, __VMLINUX_SYMBOL_STR(drm_rgb_quant_range_selectable) },
	{ 0x42f774d5, __VMLINUX_SYMBOL_STR(drm_open) },
	{ 0x723bd82c, __VMLINUX_SYMBOL_STR(drm_atomic_helper_plane_destroy_state) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=drm,drm_kms_helper,drm_mipi_dsi";

MODULE_ALIAS("of:N*T*Cbrcm,bcm2835-vc4*");

MODULE_INFO(srcversion, "E3405B0B9137B5AEFC0DF3A");
