#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x5a7ba343, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x7dc549d4, __VMLINUX_SYMBOL_STR(drm_release) },
	{ 0xc5af76d5, __VMLINUX_SYMBOL_STR(drm_prime_gem_destroy) },
	{ 0x68d99fb5, __VMLINUX_SYMBOL_STR(drm_fb_helper_set_par) },
	{ 0x6c4c447, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x26366536, __VMLINUX_SYMBOL_STR(drm_crtc_helper_set_config) },
	{ 0xb305ea25, __VMLINUX_SYMBOL_STR(drm_dev_register) },
	{ 0x4bab3d28, __VMLINUX_SYMBOL_STR(drm_connector_unplug_all) },
	{ 0x59f1c92b, __VMLINUX_SYMBOL_STR(drm_gem_put_pages) },
	{ 0xbacbed6d, __VMLINUX_SYMBOL_STR(drm_dev_alloc) },
	{ 0xaf413950, __VMLINUX_SYMBOL_STR(drm_fb_helper_initial_config) },
	{ 0x7aa1756e, __VMLINUX_SYMBOL_STR(kvfree) },
	{ 0xe7dbffbf, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0xebc54e00, __VMLINUX_SYMBOL_STR(drm_gem_dmabuf_release) },
	{ 0x234fcb0d, __VMLINUX_SYMBOL_STR(drm_mode_config_cleanup) },
	{ 0xad42c08c, __VMLINUX_SYMBOL_STR(drm_unplug_dev) },
	{ 0xc5303fb3, __VMLINUX_SYMBOL_STR(arm_dma_ops) },
	{ 0x6bc17714, __VMLINUX_SYMBOL_STR(drm_fb_helper_unlink_fbi) },
	{ 0x4e2662fd, __VMLINUX_SYMBOL_STR(dma_buf_detach) },
	{ 0xd71d3d96, __VMLINUX_SYMBOL_STR(drm_fb_helper_debug_leave) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0x4fe38dbd, __VMLINUX_SYMBOL_STR(down_interruptible) },
	{ 0x4ae2c513, __VMLINUX_SYMBOL_STR(drm_helper_probe_single_connector_modes) },
	{ 0xd5152710, __VMLINUX_SYMBOL_STR(sg_next) },
	{ 0x2928193d, __VMLINUX_SYMBOL_STR(drm_gem_free_mmap_offset) },
	{ 0x1be6df58, __VMLINUX_SYMBOL_STR(drm_vblank_cleanup) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0x9580deb, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x62b72b0d, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x9802feb3, __VMLINUX_SYMBOL_STR(drm_dev_unref) },
	{ 0x844ca90f, __VMLINUX_SYMBOL_STR(drm_vblank_init) },
	{ 0x16985ce9, __VMLINUX_SYMBOL_STR(drm_encoder_init) },
	{ 0xd697e69a, __VMLINUX_SYMBOL_STR(trace_hardirqs_on) },
	{ 0xf76b0a59, __VMLINUX_SYMBOL_STR(read_current_timer) },
	{ 0x104633d9, __VMLINUX_SYMBOL_STR(drm_connector_cleanup) },
	{ 0x20f57849, __VMLINUX_SYMBOL_STR(drm_fb_helper_unregister_fbi) },
	{ 0x25876c84, __VMLINUX_SYMBOL_STR(dma_buf_vunmap) },
	{ 0x346d28b, __VMLINUX_SYMBOL_STR(usb_get_descriptor) },
	{ 0xabafef8e, __VMLINUX_SYMBOL_STR(drm_fb_helper_pan_display) },
	{ 0xe707d823, __VMLINUX_SYMBOL_STR(__aeabi_uidiv) },
	{ 0xc02d46d9, __VMLINUX_SYMBOL_STR(drm_helper_connector_dpms) },
	{ 0x5f754e5a, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xf652ae73, __VMLINUX_SYMBOL_STR(drm_mode_connector_attach_encoder) },
	{ 0x3744cf36, __VMLINUX_SYMBOL_STR(vmalloc_to_pfn) },
	{ 0xdd4968c1, __VMLINUX_SYMBOL_STR(drm_prime_pages_to_sg) },
	{ 0x7c2c3051, __VMLINUX_SYMBOL_STR(usb_deregister) },
	{ 0xa5d49b5d, __VMLINUX_SYMBOL_STR(drm_helper_mode_fill_fb_struct) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x736d7e81, __VMLINUX_SYMBOL_STR(drm_object_attach_property) },
	{ 0xdcd882dd, __VMLINUX_SYMBOL_STR(drm_gem_handle_create) },
	{ 0xe728a35d, __VMLINUX_SYMBOL_STR(drm_gem_dumb_destroy) },
	{ 0x983803ae, __VMLINUX_SYMBOL_STR(vmap) },
	{ 0xff3b69f9, __VMLINUX_SYMBOL_STR(dma_buf_put) },
	{ 0xee8829fb, __VMLINUX_SYMBOL_STR(drm_fb_helper_fill_var) },
	{ 0xfacd2e14, __VMLINUX_SYMBOL_STR(pgprot_user) },
	{ 0x74ca77af, __VMLINUX_SYMBOL_STR(usb_control_msg) },
	{ 0xd674c78c, __VMLINUX_SYMBOL_STR(drm_send_vblank_event) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xe16b893b, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x3df64ac2, __VMLINUX_SYMBOL_STR(drm_gem_object_release) },
	{ 0x9d933e5c, __VMLINUX_SYMBOL_STR(drm_read) },
	{ 0x96a1d7e5, __VMLINUX_SYMBOL_STR(noop_llseek) },
	{ 0x6b0297cf, __VMLINUX_SYMBOL_STR(drm_add_edid_modes) },
	{ 0x4c4f3590, __VMLINUX_SYMBOL_STR(drm_fb_helper_release_fbi) },
	{ 0xdd01de2d, __VMLINUX_SYMBOL_STR(dma_buf_unmap_attachment) },
	{ 0x3bd0ccb0, __VMLINUX_SYMBOL_STR(usb_free_coherent) },
	{ 0x1dd71f7a, __VMLINUX_SYMBOL_STR(drm_err) },
	{ 0x598d19fb, __VMLINUX_SYMBOL_STR(drm_connector_init) },
	{ 0x2196324, __VMLINUX_SYMBOL_STR(__aeabi_idiv) },
	{ 0xef6613e4, __VMLINUX_SYMBOL_STR(drm_fb_helper_prepare) },
	{ 0xbf3def9a, __VMLINUX_SYMBOL_STR(drm_gem_vm_open) },
	{ 0xc6e3ef74, __VMLINUX_SYMBOL_STR(drm_mode_connector_update_edid_property) },
	{ 0x2990e9c1, __VMLINUX_SYMBOL_STR(vm_insert_page) },
	{ 0x6bea8226, __VMLINUX_SYMBOL_STR(drm_gem_vm_close) },
	{ 0x20645642, __VMLINUX_SYMBOL_STR(drm_debug) },
	{ 0x4ea1f5a2, __VMLINUX_SYMBOL_STR(drm_gem_object_free) },
	{ 0xcdd158d, __VMLINUX_SYMBOL_STR(sg_alloc_table) },
	{ 0x99881acd, __VMLINUX_SYMBOL_STR(drm_gem_prime_fd_to_handle) },
	{ 0xa41a288a, __VMLINUX_SYMBOL_STR(dma_buf_begin_cpu_access) },
	{ 0x703103f, __VMLINUX_SYMBOL_STR(drm_ioctl) },
	{ 0x33d2dd38, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_imageblit) },
	{ 0x1f9d0e3, __VMLINUX_SYMBOL_STR(usb_submit_urb) },
	{ 0xf0142e77, __VMLINUX_SYMBOL_STR(drm_gem_mmap) },
	{ 0xe28bead9, __VMLINUX_SYMBOL_STR(dma_buf_map_attachment) },
	{ 0xe235c62b, __VMLINUX_SYMBOL_STR(dma_buf_export) },
	{ 0xa413a109, __VMLINUX_SYMBOL_STR(drm_framebuffer_unregister_private) },
	{ 0xbb4f295d, __VMLINUX_SYMBOL_STR(put_device) },
	{ 0x2a8845c7, __VMLINUX_SYMBOL_STR(drm_fb_helper_check_var) },
	{ 0x30a6a6be, __VMLINUX_SYMBOL_STR(drm_fb_helper_blank) },
	{ 0xe9226938, __VMLINUX_SYMBOL_STR(drm_gem_object_lookup) },
	{ 0x9777bbd5, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x39eb52e3, __VMLINUX_SYMBOL_STR(drm_fb_helper_alloc_fbi) },
	{ 0x22186649, __VMLINUX_SYMBOL_STR(drm_crtc_init) },
	{ 0xd1f7271a, __VMLINUX_SYMBOL_STR(dma_buf_attach) },
	{ 0xc3dbe906, __VMLINUX_SYMBOL_STR(drm_gem_prime_handle_to_fd) },
	{ 0xe512b542, __VMLINUX_SYMBOL_STR(get_device) },
	{ 0xaa8ecff4, __VMLINUX_SYMBOL_STR(drm_connector_unregister) },
	{ 0xe30c23c, __VMLINUX_SYMBOL_STR(drm_gem_object_init) },
	{ 0x9b403553, __VMLINUX_SYMBOL_STR(drm_encoder_cleanup) },
	{ 0x62f81f03, __VMLINUX_SYMBOL_STR(fb_deferred_io_cleanup) },
	{ 0x5749b11b, __VMLINUX_SYMBOL_STR(fb_deferred_io_init) },
	{ 0xa1aa831c, __VMLINUX_SYMBOL_STR(drm_gem_create_mmap_offset) },
	{ 0x12036aa, __VMLINUX_SYMBOL_STR(drm_mode_create_dirty_info_property) },
	{ 0x4cd48b95, __VMLINUX_SYMBOL_STR(drm_crtc_cleanup) },
	{ 0x28d6861d, __VMLINUX_SYMBOL_STR(__vmalloc) },
	{ 0xaf8a3a0e, __VMLINUX_SYMBOL_STR(drm_mode_config_init) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x94961283, __VMLINUX_SYMBOL_STR(vunmap) },
	{ 0x9c0bbeb9, __VMLINUX_SYMBOL_STR(remap_pfn_range) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x364b3fff, __VMLINUX_SYMBOL_STR(up) },
	{ 0x2762eaf9, __VMLINUX_SYMBOL_STR(usb_register_driver) },
	{ 0x1db7dc40, __VMLINUX_SYMBOL_STR(pgprot_kernel) },
	{ 0xe5fb6b1b, __VMLINUX_SYMBOL_STR(drm_fb_helper_fini) },
	{ 0x6fb790d2, __VMLINUX_SYMBOL_STR(drm_modeset_lock_all) },
	{ 0x9cd60539, __VMLINUX_SYMBOL_STR(sg_free_table) },
	{ 0x3e884f4b, __VMLINUX_SYMBOL_STR(vm_get_page_prot) },
	{ 0xf204c797, __VMLINUX_SYMBOL_STR(drm_prime_sg_to_page_addr_arrays) },
	{ 0x1fc7c715, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_fillrect) },
	{ 0xa4885c26, __VMLINUX_SYMBOL_STR(drm_modeset_unlock_all) },
	{ 0xb5857bc2, __VMLINUX_SYMBOL_STR(drm_helper_disable_unused_functions) },
	{ 0xe51db56b, __VMLINUX_SYMBOL_STR(dma_buf_end_cpu_access) },
	{ 0x4edfafc, __VMLINUX_SYMBOL_STR(drm_fb_helper_setcmap) },
	{ 0x7c1e504d, __VMLINUX_SYMBOL_STR(usb_alloc_coherent) },
	{ 0xaccd8d71, __VMLINUX_SYMBOL_STR(drm_framebuffer_init) },
	{ 0xc360e7e2, __VMLINUX_SYMBOL_STR(drm_ut_debug_printk) },
	{ 0xc5cf9b9f, __VMLINUX_SYMBOL_STR(dma_buf_vmap) },
	{ 0x3fdd94e0, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_copyarea) },
	{ 0xee44278e, __VMLINUX_SYMBOL_STR(drm_gem_get_pages) },
	{ 0xec3d2e1b, __VMLINUX_SYMBOL_STR(trace_hardirqs_off) },
	{ 0x9e70e990, __VMLINUX_SYMBOL_STR(drm_fb_helper_fill_fix) },
	{ 0x7b1ceca2, __VMLINUX_SYMBOL_STR(drm_connector_register) },
	{ 0x3ac1fef9, __VMLINUX_SYMBOL_STR(drm_mode_legacy_fb_format) },
	{ 0xc0acaaa0, __VMLINUX_SYMBOL_STR(usb_free_urb) },
	{ 0xc57877cd, __VMLINUX_SYMBOL_STR(down_timeout) },
	{ 0xcea39e95, __VMLINUX_SYMBOL_STR(drm_kms_helper_poll_disable) },
	{ 0xb0f6da9, __VMLINUX_SYMBOL_STR(drm_mode_object_find) },
	{ 0xb2356ef3, __VMLINUX_SYMBOL_STR(drm_fb_helper_debug_enter) },
	{ 0xe4832020, __VMLINUX_SYMBOL_STR(drm_poll) },
	{ 0x6c4e7fd0, __VMLINUX_SYMBOL_STR(drm_fb_helper_init) },
	{ 0xdd17e226, __VMLINUX_SYMBOL_STR(drm_fb_helper_single_add_all_connectors) },
	{ 0x6f22b514, __VMLINUX_SYMBOL_STR(usb_alloc_urb) },
	{ 0x42f774d5, __VMLINUX_SYMBOL_STR(drm_open) },
	{ 0xb56bcbcc, __VMLINUX_SYMBOL_STR(drm_framebuffer_cleanup) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=drm,drm_kms_helper";

MODULE_ALIAS("usb:v17E9p*d*dc*dsc*dp*icFFisc00ip00in*");

MODULE_INFO(srcversion, "ABC4023F73116DB27CE21DF");
